apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: health-check-example-sozc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: health-check-example-sozc
    app.kubernetes.io/part-of: snowdrop
  name: health-check-example-sozc
  namespace: cmoullia-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: health-check-example-sozc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: health-check-example-sozc
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:4554c8b86cf9dbc8cc25ddd782d160290117d7024818da3c78e83c4a19572353
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
