apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: health-check-example-v7qw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: health-check-example-v7qw
    app.kubernetes.io/part-of: snowdrop
  name: health-check-example-v7qw
  namespace: cmoullia-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: health-check-example-v7qw
    weight: 100
status: {}
